name       : vc-intrinsics
version    : 0.5.0
release    : 2
source     :
    - git|https://github.com/intel/vc-intrinsics.git : v0.5.0
license    : MIT
component  : programming.devel
summary    : VC Intrinsics project contains a set of new intrinsics on top of core LLVM IR instructions that represent SIMD semantics of a program targeting GPU
description: |
    VC Intrinsics project contains a set of new intrinsics on top of core LLVM IR instructions that represent SIMD semantics of a program targeting GPU
clang      : yes
# headers only package
patterns   :
    - /*
setup      : |
    %cmake \
        -DLLVM_DIR=/usr/lib64/cmake/llvm \
build      : |
    %make
install    : |
    %make_install
